In [1]:
#Numpy
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(arr)

print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [2]:
import numpy as np

arr = np.array(42)

print(arr)

42


In [3]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

print(arr)

[[1 2 3]
 [4 5 6]]


In [4]:
import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])


print(arr)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [2]:
#arrange
import numpy as np
array = np.arange(2, 10, 2)
print(array)


[2 4 6 8]


In [5]:
#min max
import numpy as np
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
print(np.min(arr))
print(np.max(arr))

1
6


In [ ]:
#

In [1]:
#indexing
import numpy as np

arr = np.array([1, 2, 3, 4])

print(arr[2] + arr[3])

arr1 = ([[1, 2, 3], [4, 5, 6]])
arr2=  ([[9, 4, 10], [11, ,7, 8]])



7
